// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	http "net/http"


	mock "github.com/stretchr/testify/mock"
	"github.com/ttanik/http-client/httperror"

)

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

// ExecuteRequest provides a mock function with given fields: request
func (_m *Requester) ExecuteRequest(request *http.Request) (*http.Response, *httperror.HTTPError) {
	ret := _m.Called(request)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 *httperror.HTTPError
	if rf, ok := ret.Get(1).(func(*http.Request) *httperror.HTTPError); ok {
		r1 = rf(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*httperror.HTTPError)
		}
	}

	return r0, r1
}
